SERVICE_HOST: localhost
SERVICE_PORT: 8080
server:
  servlet:
    context-path: '/api'
spring:
  redis:
    host : localhost
    port : 6379
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: false
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
        data:
          rest:
            #base-path: /rest
            detection-strategy:  ANNOTATED